#!/bin/sh
#
# link-local IP addresses and are not redistributed by Babel.
# To make sure we dont accidentally use them, we swap them out for the main IP address of the node
# when originating traffic locally and destined for one of these network interfaces.
#

main_ip="$(uci -q -c /etc/config.mesh get setup.globals.wifi_ip)"

nft insert rule inet fw4 srcnat ip saddr 169.254.0.0/16 fib daddr type != broadcast snat to ${main_ip} comment \"SNAT traffic to hide the link-local IP\"
