#!/bin/sh

# add custom firewall rules into this file to preserve across
# sysupgrades

# example rules to forward from home network
# to access an ipCam somewhere on the mesh
# on home network use the IP address of the WAN assigned to the mesh node
# to access the ipcam, e.g.  http://192.168.1.59:8082

#nft add rule ip fw4 prerouting_wan                                     tcp dport 8082 counter dnat to <IP address of ipcam>
#nft add rule ip fw4 postrouting_wan     ip daddr <IP address of ipcam> tcp dport 80   counter snat to <IP wifi on this node>    comment \"my mesh ipCam\"
#nft add rule ip fw4 postrouting_dtdlink ip daddr <IP address of ipcam> tcp dport 80   counter snat to <IP dtdlink on this node> comment \"my mesh ipCam\"
