#!/bin/sh

# add custom firewall rules into this file to preserve across
# sysupgrades

# example rules to forward from home network
# to access an ipCam somewhere on the mesh
# on home network use the IP address of the WAN assigned to the mesh node
# to access the ipcam, e.g.  http://192.168.1.59:8082

#iptables -t nat -A zone_wan_prerouting       -p tcp -m tcp --dport 8082 		-j DNAT		    --to <IP address of ipcam>            -m comment --comment "my mesh ipCam"
#iptables -t nat -A zone_wifi_postrouting     -p tcp -m tcp -d <IP address of ipcam>	-j SNAT --dport 80  --to-source <IP wifi on this node>    -m comment --comment "my mesh ipCam"
#iptables -t nat -A zone_dtdlink_postrouting  -p tcp -m tcp -d <IP address of ipcam>	-j SNAT --dport 80  --to-source <IP dtdlink on this node> -m comment --comment "my mesh ipCam"

