#
# Enable ECN for better tcp management in the network. The default value is 2
# which means we only respond positively to an ECN request, but don't initiate.
# This will make sure we initiate also.
#
net.ipv4.tcp_ecn = 1
