#!/usr/bin/perl
=for commnet

  Part of BBHN Mesh -- Used for creating Amateur Radio friendly mesh networks
  Copyright (C) 2015 Conrad Lara
   See Contributors file for additional contributors

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation version 3 of the License.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

=cut

print "Content-type:text\r\n\r\n";

$ispermitencblock = `opkg list-installed blockknownencryption|wc -l`;
chomp($ispermitencblock);

if ($ispermitencblock){
    print "Encrypted Traffic: Blocked\n";
} else {
    print "Encrypted Traffic: Allowed\n";
}

print "Active firewall rules:\n";
system ("/usr/sbin/iptables -L");
