#!/usr/bin/lua
--[[

	Copyright (C) 2022 Tim Wilkinson
	See Contributors file for additional contributors

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation version 3 of the License.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.

	Additional Terms:

	Additional use restrictions exist on the AREDN(TM) trademark and logo.
		See AREDNLicense.txt for more info.

	Attributions to the AREDN Project must be retained in the source code.
	If importing this code into a new or existing project attribution
	to the AREDN project must be added to the source code.

	You must not misrepresent the origin of the material contained within.

	Modified versions must be modified to attribute to the original source
	and be marked in reasonable ways as differentiate it from the original
	version

--]]

require("uci")
require("aredn.http")
require("aredn.hardware")
local html = require("aredn.html")
local info = require("aredn.info")

if uci.cursor():get("aredn", "@lqm[0]", "enable") ~= "1" then
    print "Content-type: text/text\r"
    print "Cache-Control: no-store\r"
    print "\r"
    print "Disabled"
    os.exit()
end


http_header()
html.header(info.get_nvram("node") .. " Neighbor Link Status")
html.print("<body>")
html.alert_banner()
html.print([[
    <style>
        body {
            font-size: 14px;
            padding: 16px;
        }
        .title {
            font-size: 20px;
            padding: 20px 0;
            text-align: center;
        }
        .lt {
            font-weight: bold;
            padding: 12px 0 4px 0;
        }
        #links {
            padding-bottom: 16px;
            min-height: 300px;
        }
        #links > div {
            padding: 2px 0;
        }
        .m, .b {
            display: inline-block;
            width: 190px;
        }
        .s {
            display: inline-block;
            width: 80px;
        }
        .p {
            display: inline-block;
            width: 120px;
        }
    </style>
    <center>
        <table width=790>
            <tr><td>
            <hr><table cellpadding=5 border=0 width=100%><tr>
            <td align=center width=15%><a href='status'>Node Status</a></td>
            <td align=center width=15%><a href='setup'>Basic Setup</a></td>
            <td align=center width=15%><a href='ports'>Port Forwarding,<br>DHCP, and Services</a></td>
            <td align=center width=15%><a href='vpn'>Tunnel<br>Server</a></td>
            <td align=center width=15%><a href='vpnc'>Tunnel<br>Client</a></td>
            <td align=center width=15%><a href='admin'>Administration</a></td>
            <td align=center width=15%><a href='advancedconfig'>Advanced<br>Configuration</a></td>
            </tr></table><hr>
            </td></tr>
            <tr><td>
                <div class="title">Neighbor Link Status</div>
                <div class="lt">
                    <span class="m">Link</span><span class="s">SNR</span><span class="p">Distance</span><span class="s">Quality</span><span class="p">TX Estimate</span><span class="b">Status</span>
                </div>
                <div id="links"></div>
                </td></tr>
            </table>
    </center>
    <script>
        const meters_to_miles = 0.000621371;
        const wifi_scale = 0.2;
        const status = track => {
            if (track.blocked) {
                if (track.blocks.user) {
                    return "blocked - user";
                }
                if (track.blocks.dtd) {
                    return "blocked - dtd";
                }
                if (track.blocks.signal) {
                    return "blocked - signal";
                }
                if (track.blocks.distance) {
                    return "blocked - distance";
                }
                if (track.blocks.dup) {
                    return "blocked - dup";
                }
                return "blocked";
            }
            if (track.pending) {
                return "pending";
            }
            if (track.routable) {
                return "active";
            }
            return "idle";
        }
        const name = track => {
            if (track.hostname || track.ip) {
                return `<a href="http://${track.hostname || track.ip}:8080">${track.hostname || track.ip}</a>`;
            }
            return track.mac || "-";
        }
        const update = data => {
            let links = "";
            for (let mac in data.info.trackers) {
                const track = data.info.trackers[mac];
                let txspeed = "-";
                let txquality = "-";
                if (!track.blocked) {
                    txspeed = (track.station.tx_rate * wifi_scale).toFixed(2) + " Mb/s";
                }
                if (typeof track.tx_quality === "number") {
                    txquality = track.tx_quality + "%";
                }
                links += `<div><span class="m">${name(track)}</span><span class="s">${track.snr}${"rev_snr" in track ? "/" + track.rev_snr : ""}</span><span class="p">${"distance" in track ? (meters_to_miles * track.distance).toFixed(2) + " miles" : "-"}</span><span class="s">${txquality}</span><span class="p">${txspeed}</span><span class="b">${status(track)}</span></div>`;
            }
            document.getElementById("links").innerHTML = links;
        }
        const fetchAndUpdate = () => {
            fetch("/cgi-bin/sysinfo.json?lqm=1").then(r => r.json()).then(data => {
                update(data.lqm);
                setTimeout(fetchAndUpdate, 60000);
            }).catch(_ => {
                setTimeout(fetchAndUpdate, 30000);
            });
        }
        fetchAndUpdate();
    </script>]])
html.footer()
html.print("</body></html>")
http_footer()
