#!/usr/bin/lua
--[[

    Part of AREDN -- Used for creating Amateur Radio Emergency Data Networks
    Copyright (C) 2023 Tim Wilkinson
    See Contributors file for additional contributors

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Additional Terms:

    Additional use restrictions exist on the AREDN(TM) trademark and logo.
        See AREDNLicense.txt for more info.

    Attributions to the AREDN Project must be retained in the source code.
    If importing this code into a new or existing project attribution
    to the AREDN project must be added to the source code.

    You must not misrepresent the origin of the material contained within.

    Modified versions must be modified to attribute to the original source
    and be marked in reasonable ways as differentiate it from the original
    version

--]]

package.path = package.path .. ";/usr/local/bin/?.lua"

require("nixio")

local gzip = (os.getenv("HTTP_ACCEPT_ENCODING") or ""):match("gzip")

print "Content-type: text/plain; version=0.0.4\r"
print "Cache-Control: no-store\r"
if gzip then
    print "Content-Encoding: gzip\r"
end
print("Access-Control-Allow-Origin: *\r")
print("\r")

local output = nil
if gzip then
    io.flush()
    output = io.popen("gzip", "w")
    function print(line)
        output:write(line .. "\n")
    end
end

-- Find, sort then generate the metrics to be returned
local metrics = {}
for m in nixio.fs.dir("/usr/local/bin/metrics/")
do
    m = m:match("^(.*)%.lua$")
    if m then
        metrics[#metrics + 1] = "metrics." .. m
    end
end
table.sort(metrics);
for _, m in ipairs(metrics)
do
    local ok, err = pcall(function() require(m) end)
    if not ok then
        nixio.syslog("err", err)
    end
end

-- Touch a file so we know when this was last done
io.open("/tmp/metrics-ran", "w+"):close()

if output then
    output:close()
else
    io.flush()
end
