#!/usr/bin/perl

$debug = 0;

BEGIN {push @INC, '/www/cgi-bin'};
use perlfunc;

# collect some variables
$node = nvram_get("node");
$node = "NOCALL" if $node eq "";

read_postdata();

system "mkdir -p /tmp/web";
system "/usr/local/bin/wscan -w > /tmp/web/wscan.next" unless $parms{stop};
system "touch /tmp/web/autoscan" if $parms{auto};
system "rm -f /tmp/web/autoscan" if $parms{stop};
system "mv /tmp/web/wscan.next /tmp/web/wscan" unless $parms{stop};

# generate the page
http_header();
html_header("$node WiFi scan", 0);
print "<meta http-equiv='refresh' content='5;url=/cgi-bin/scan'>\n" if -f "/tmp/web/autoscan";
print "</head>\n";
print "<body><form method=post action=/cgi-bin/scan enctype='multipart/form-data'>\n";
print "<center>\n";
print "<h1>$node WiFi scan</h1><hr>\n";

if(-f "/tmp/web/autoscan")
{
    print "<input type=submit name=stop value=Stop title='Abort continuous scan'>\n";
}
else
{
    print "<input type=submit name=refresh value=Refresh title='Refresh this page'>\n";
    print "&nbsp;&nbsp;&nbsp;\n";
    print "<input type=submit name=auto value=Auto title='Begin continuous scan'>\n";
}

print "&nbsp;&nbsp;&nbsp;\n";
print "<button type=button onClick='window.location=\"status\"' title='Return to status page'>Quit</button><br><br>\n";
system "cat /tmp/web/wscan";
print "<br>";
print "</center>\n";
print "</form>\n";

show_debug_info();
show_parse_errors();

print "</body>\n";
print "</html>\n";
