#!/usr/bin/lua
--[[

    Part of AREDN® -- Used for creating Amateur Radio Emergency Data Networks
    Copyright (C) 2024 Tim Wilkinson
    See Contributors file for additional contributors

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Additional Terms:

    Additional use restrictions exist on the AREDN® trademark and logo.
        See AREDNLicense.txt for more info.

    Attributions to the AREDN® Project must be retained in the source code.
    If importing this code into a new or existing project attribution
    to the AREDN® project must be added to the source code.

    You must not misrepresent the origin of the material contained within.

    Modified versions must be modified to attribute to the original source
    and be marked in reasonable ways as differentiate it from the original
    version

--]]

require("aredn.hardware");
require("iwinfo")

local q = os.getenv("QUERY_STRING") or ""
local mac = q:match("mac=([^&]*)") or "00:00:00:00:00:00"

local wifiiface = aredn.hardware.get_iface_name("wifi")
local nf = iwinfo.nl80211.noise(wifiiface) or -95

print("Content-type: application/json\r")
print("Cache-Control: no-store\r")
print("Access-Control-Allow-Origin: *\r")
print("\r")

local signal = nf
local f = io.popen("/usr/sbin/iw " .. wifiiface .. " station get " .. mac .. " 2>/dev/null")
if f then
    for line in f:lines()
    do
        local s = line:match("signal:%s+(%S+)%s+")
        if s then
            signal = s
            break
        end
    end
    f:close()
end

print('{"s":' .. signal .. ',"n":' .. nf .. '}')
