#!/usr/bin/perl

BEGIN {push @INC, '/www/cgi-bin'};
use perlfunc;

http_header();
html_header("$node system information", 1);
print "<body><pre>\n";

print " node: ", nvram_get("node"), "\n";
print "model: ", `/usr/local/bin/get_model`, "\n";

foreach(`ifconfig -a`)
{
    next unless /^(\S+) .*HWaddr (\S+)/;
    printf "%-6s %s\n", $1, $2;
}

print "\n/proc/cpuinfo\n";
system "cat /proc/cpuinfo";

print "\nnvram\n";
system "uci -c /etc/local/uci show 2>&1";

print "</pre>\n";
print "</body>\n";
print "</html>\n";
