#!/usr/bin/perl

BEGIN {push @INC, '/www/cgi-bin'};
use perlfunc;

http_header();
html_header("$node system information", 1);
print "<body><pre>\n";

print " node: ", nvram_get("node"), "\n";
print "model: ", `/usr/local/bin/get_model`, "\n";

if ( is_hardware_supported() !=1  ){
    print "<font color=\"red\">!!!! UNSUPPORTED DEVICE !!!!</font>\n";
    print "boardid: " , hardware_boardid() , "\n";
    if ( is_hardware_supported == 0 ) {
        print "<font color=\"red\">Device HAS BEEN TESTED AS UNSUPPORTED</font>\n";
    }
    else {
        print "<font color=\"red\">Device has not been tested. Please file a ticket with your experiences.</font>\n";
    }
    print "\n";
}

foreach(`ifconfig -a`)
{
    next unless /^(\S+) .*HWaddr (\S+)/;
    printf "%-6s %s\n", $1, $2;
}

print "\n/proc/cpuinfo\n";
system "cat /proc/cpuinfo";

print "\nnvram\n";
system "uci -c /etc/local/uci show 2>&1";

print "</pre>\n";
print "</body>\n";
print "</html>\n";
