#!/bin/sh

. /lib/functions.sh

if [ "${ACTION}" = "add" -a "$(uci -q get wireless.${DEVICENAME}.network)" = "wifi" -a "$(uci -q get wireless.${DEVICENAME}.mode)" = "sta" ]; then
    radio=$(echo ${DEVICENAME} | sed s/wlan/radio/)
    channels="$(uci -q -c /etc/config.mesh get setup.globals.${radio}_channels)"
    WPA_CLI="/usr/sbin/wpa_cli"
    CTRL="/var/run/wpa_supplicant"
    if [ "$(uci -q get wireless.${radio}.band)" = "s1g" ]; then
        WPA_CLI="/usr/sbin/wpa_cli_s1g"
        CTRL="/var/run/wpa_supplicant_s1g"
    fi
    if [ "${channels}" != "${channels#* }" ]; then
        # Wait for the socket to become available
        count=0
        while [ ! -S "${CTRL}/${DEVICENAME}" -a ${count} -lt 10 ]; do
            sleep 1
            count=$((count+1))
        done
        if [ -S "${CTRL}/${DEVICENAME}" ]; then
            # Once it is, add the ssids for the channel selection
            bandwidth="$(uci -q -c /etc/config.mesh get setup.globals.${radio}_bandwidth)"
            ssid="$(uci -q -c /etc/config.mesh get setup.globals.${radio}_ssid)"
            ${WPA_CLI} -i "${DEVICENAME}" -p "${CTRL}" remove_network all
            for channel in ${channels}
            do
                id=$(${WPA_CLI} -i "${DEVICENAME}" -p "${CTRL}" add_network | tail -1)
                ${WPA_CLI} -i "${DEVICENAME}" -p "${CTRL}" set_network "${id}" ssid "\"${ssid}-${channel}-${bandwidth}-v3\""
                ${WPA_CLI} -i "${DEVICENAME}" -p "${CTRL}" set_network "${id}" key_mgmt NONE
                ${WPA_CLI} -i "${DEVICENAME}" -p "${CTRL}" enable_network "${id}"
            done
            ${WPA_CLI} -i "${DEVICENAME}" -p "${CTRL}" reassociate
        fi
    fi
fi
