#! /bin/sh
if [ -e /etc/config/dmz-mode ] ; then
    /sbin/uci -q -c /etc/config.mesh add aredn dmz
    /sbin/uci -q -c /etc/config.mesh set aredn.@dmz[0].mode=$(cat /etc/config/dmz-mode)
    /sbin/uci -q -c /etc/config.mesh commit aredn
    rm -f /etc/config/dmz-mode
elif [ "$(/sbin/uci -q -c /etc/config.mesh get aredn.@dmz[0].mode)" = "" ]; then
    /sbin/uci -q -c /etc/config.mesh add aredn dmz
    /sbin/uci -q -c /etc/config.mesh set aredn.@dmz[0].mode=0
    /sbin/uci -q -c /etc/config.mesh commit aredn
fi
