#! /bin/sh
VER=$(jsonfilter -e '@.system.compat_version' < /etc/board.json)
if [ "${VER}" != "" ]; then
    sed -i "s/^compat_version = 1.0/compat_version = ${VER}/" /etc/config.mesh/_setup
    sed -i "s/^compat_version = 1.0/compat_version = ${VER}/" /etc/config.mesh/_setup.default
    uci -q set system.@system[0].compat_version=${VER}
    uci -q commit system
fi
