#! /bin/sh
case "$(/usr/local/bin/get_boardid)" in
    MikroTik\ hAP\ ac2)
        sed -i "s/^compat_version = 1.0/compat_version = 1.1/" /etc/config.mesh/_setup
        sed -i "s/^compat_version = 1.0/compat_version = 1.1/" /etc/config.mesh/_setup.default
        /sbin/uci -q set system.@system[0].compat_version=1.1
        /sbin/uci -q commit system
        ;;
    *)
        ;;
esac
