#!/bin/sh
true <<'LICENSE'
  Part of AREDN -- Used for creating Amateur Radio Emergency Data Networks
  Copyright (C) 2024 Tim Wilkinson
  See Contributors file for additional contributors

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation version 3 of the License.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

  Additional Terms:

  Additional use restrictions exist on the AREDN(TM) trademark and logo.
    See AREDNLicense.txt for more info.

  Attributions to the AREDN Project must be retained in the source code.
  If importing this code into a new or existing project attribution
  to the AREDN project must be added to the source code.

  You must not misrepresent the origin of the material contained within.

  Modified versions must be modified to attribute to the original source
  and be marked in reasonable ways as differentiate it from the original
  version.

LICENSE

cat > /tmp/setup_migrate << __EOF__

require("nixio")
require("uci")

io.open("/etc/config.mesh/setup", "a"):close()
local c = uci.cursor("/etc/config.mesh")

-- Migrate the old school _setup file
if not c:get("setup", "globals") and nixio.fs.stat("/etc/config.mesh/_setup") then
    c:set("setup", "globals", "globals")
    for line in io.lines("/etc/config.mesh/_setup")
    do
        if not (line:match("^%s*#") or line:match("^%s*$")) then
            local k, v = line:match("^(%S+)%s*=%s*(.*)%s*$")
            if v then
                c:set("setup", "globals", k, v)
            end
        end
    end
    c:commit("setup")
end

-- Migrate the old school _setup.services.{nat,dmz} files
if not c:get("setup", "services") then
    local file = "/etc/config.mesh/_setup.services."
    if (nixio.fs.stat(file .. "nat", "size") or -1) > 0 then
        file = file .. "nat"
    elseif (nixio.fs.stat(file .. "dmz", "size") or -1) > 0 then
        file = file .. "dmz"
    else
        file = nil
    end
    if file then
        local services = {}
        for line in io.lines(file)
        do
            services[#services + 1] = line
        end
        c:set("setup", "services", "services")
        c:set("setup", "services", "service", services)
        c:commit("setup")
    end
end

-- Migrate the old school _setup.dhcp.{nat,dmz} files
if not c:get("setup", "dhcpreservations") then
    local file = "/etc/config.mesh/_setup.dhcp."
    if (nixio.fs.stat(file .. "nat", "size") or -1) > 0 then
        file = file .. "nat"
    elseif (nixio.fs.stat(file .. "dmz", "size") or -1) > 0 then
        file = file .. "dmz"
    else
        file = nil
    end
    if file then
        local dhcp = {}
        for line in io.lines(file)
        do
            dhcp[#dhcp + 1] = line
        end
        c:set("setup", "dhcpreservations", "dhcpreservations")
        c:set("setup", "dhcpreservations", "reservation", dhcp)
        c:commit("setup")
    end
end

-- Migrate the old school _setup.dhcptags.{nat,dmz} files
if not c:get("setup", "dhcptags") then
    local file = "/etc/config.mesh/_setup.dhcptags."
    if (nixio.fs.stat(file .. "nat", "size") or -1) > 0 then
        file = file .. "nat"
    elseif (nixio.fs.stat(file .. "dmz", "size") or -1) > 0 then
        file = file .. "dmz"
    else
        file = nil
    end
    if file then
        local dhcp = {}
        for line in io.lines(file)
        do
            dhcp[#dhcp + 1] = line
        end
        c:set("setup", "dhcptags", "dhcptags")
        c:set("setup", "dhcptags", "tag", dhcp)
        c:commit("setup")
    end
end

-- Migrate the old school _setup.dhcpoptions.{nat,dmz} files
if not c:get("setup", "dhcpoptions") then
    local file = "/etc/config.mesh/_setup.dhcpoptions."
    if (nixio.fs.stat(file .. "nat", "size") or -1) > 0 then
        file = file .. "nat"
    elseif (nixio.fs.stat(file .. "dmz", "size") or -1) > 0 then
        file = file .. "dmz"
    else
        file = nil
    end
    if file then
        local dhcp = {}
        for line in io.lines(file)
        do
            dhcp[#dhcp + 1] = line
        end
        c:set("setup", "dhcpoptions", "dhcpoptions")
        c:set("setup", "dhcpoptions", "option", dhcp)
        c:commit("setup")
    end
end

-- Dont remove this yet otherwise we cannot revert this node
-- os.remove("/etc/config.mesh/_setup")
-- os.remove("/etc/config.mesh/_setup.service.dmz")
-- os.remove("/etc/config.mesh/_setup.service.nat")
-- os.remove("/etc/config.mesh/_setup.dhcp.dmz")
-- os.remove("/etc/config.mesh/_setup.dhcp.nat")
-- os.remove("/etc/config.mesh/_setup.dhcptags.dmz")
-- os.remove("/etc/config.mesh/_setup.dhcptags.nat")
-- os.remove("/etc/config.mesh/_setup.dhcpoptions.dmz")
-- os.remove("/etc/config.mesh/_setup.dhcpoptions.nat")

__EOF__
/usr/bin/lua /tmp/setup_migrate
rm -f /tmp/setup_migrate
