#!/bin/sh

cat > /etc/httpd.conf <<'EOF'
/cgi-bin/setup:root:$p$root
/cgi-bin/ports:root:$p$root
/cgi-bin/admin:root:$p$root
/cgi-bin/vpn:root:$p$root
/cgi-bin/vpnc:root:$p$root
/cgi-bin/supporttool:root:$p$root
/cgi-bin/scan:root:$p$root
/cgi-bin/advancedconfig:root:$p$root
EOF
