#!/bin/sh
# Fix mac addresses as necessary

fix=""

eth0=$(ifconfig eth0 2> /dev/null | grep HWaddr | sed s/^.*HWaddr\ //)
wlan0=$(ifconfig wlan0 2> /dev/null | grep HWaddr | sed s/^.*HWaddr\ //)
if [ "$eth0" = "$wlan0" -a "$eth0" != "" ]; then
    fix="lan wan dtdlink"
fi

mkdir -p /etc/aredn_include

for i in $fix
do
    if [ ! -s /etc/aredn_include/fixedmac.$i ]; then
        mac=$(hexdump -n5 -e'/5 "02" 5/1 ":%02X"' /dev/random)
        echo -e "\toption\tmacaddr\t$mac" > /etc/aredn_include/fixedmac.$i
    fi
done
