#!/bin/sh
# Fix mac addresses as necessary

fix=""

eth0=$(ifconfig eth0 2> /dev/null | grep HWaddr | sed s/^.*HWaddr\ // | sed s/\ //g)
wlan0=$(ifconfig wlan0 2> /dev/null | grep HWaddr | sed s/^.*HWaddr\ // | sed s/\ //g)
brlan=$(ifconfig br-lan 2> /dev/null | grep HWaddr | sed s/^.*HWaddr\ // | sed s/\ //g)

if [ "$eth0" = "$wlan0" -a "$eth0" != "" ]; then
    fix="lan wan dtdlink"
elif [ "$wlan0" = "" ]; then
    fix="lan"
elif [ "$brlan" = "00:03:7F:11:23:C6" ]; then # Fix AR300M
    fix="lan"
else
    delta=$((0x${wlan0//:/} - 0x${brlan//:/}))
    if [ $delta -ge -10 -a $delta -le 10 ]; then # Fix some Mikrotik
        fix="lan"
    fi
fi

mkdir -p /etc/aredn_include

for i in $fix
do
    if [ ! -s /etc/aredn_include/fixedmac.$i ]; then
        mac=$(hexdump -n5 -e'/5 "02" 5/1 ":%02X"' /dev/random)
        echo -e "\toption\tmacaddr\t$mac" > /etc/aredn_include/fixedmac.$i
    fi
done
