#!/bin/sh

uci set wireless.radio0.channel=`perl -I/www/cgi-bin -e 'use channelmaps; $channels = rf_channels_list(); foreach  $channelnumber (sort {$a <=> $b} keys %{$channels} ) { print $channelnumber; exit 0;}'`
uci -q commit
