#!/bin/sh /etc/rc.common

USE_PROCD=1
START=91

start_service() {
    procd_open_instance iperf3
    procd_set_param command /usr/bin/iperf3 -s -D
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/iperf3.pid
    procd_set_param user root
    procd_close_instance
}
