#!/bin/sh /etc/rc.common
START=70

start() {
  {
    while ! ping -c1 us.pool.ntp.org >/dev/null 2>&1; do sleep 60; done
    /usr/sbin/ntpclient -s -l -h us.pool.ntp.org >/dev/null 2>&1;
  } &
}

stop() {
  killall ntpclient
}

