#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=50

BIN=olsrd
DEFAULT=/etc/default/olsrd
RUN_D=/var/run
PID_F=$RUN_D/$BIN.pid

start() {
	# generate the config file
        /usr/local/bin/olsrd-config || exit 1

	# start the daemon
	[ -f $DEFAULT ] && . $DEFAULT
	$BIN -f /tmp/olsrd.conf -nofork $OPTIONS &
	
	# write pid file (but strip out own pid ($$))
	mkdir -p $RUN_D
	PID=`pidof $BIN`
	echo ${PID%$$} > $PID_F
}

stop() {
	killall olsrd
}

