#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=45
boot() {

  [ -x /usr/local/bin/nvram-setup ] &&  /usr/local/bin/nvram-setup

  [ -x /usr/local/bin/aredn_postupgrade ] && /usr/local/bin/aredn_postupgrade

}
