#!/usr/bin/lua
--[[

	Part of AREDN® -- Used for creating Amateur Radio Emergency Data Networks
	Copyright (C) 2023 Tim Wilkinson
	See Contributors file for additional contributors

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation version 3 of the License.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.

	Additional Terms:

	Additional use restrictions exist on the AREDN® trademark and logo.
		See AREDNLicense.txt for more info.

	Attributions to the AREDN® Project must be retained in the source code.
	If importing this code into a new or existing project attribution
	to the AREDN® project must be added to the source code.

	You must not misrepresent the origin of the material contained within.

	Modified versions must be modified to attribute to the original source
	and be marked in reasonable ways as differentiate it from the original
	version

--]]

require("nixio")
require("luci.jsonc")

local package_store = "/etc/package_store"
local package_catalog = package_store .. "/catalog.json"

if nixio.fs.stat(package_catalog) then
	-- Make sure we can contact the package server before proceeding.
	-- We'll wait a few minutes before going ahead anyway
	for i = 1,5
	do
		if os.execute("ping -q -c 1 -W 5 downloads.arednmesh.org > /dev/null 2>&1") == 0 then
			break
		end
		print("Failed to contact package server - retry in 60 seconds")
		nixio.nanosleep(60, 0)
	end

    os.execute("opkg update")
    local catalog = luci.jsonc.parse(io.open(package_catalog):read("*a"))
    for ipkg, state in pairs(catalog.installed)
    do
        if state == "local" then
            local file = package_store .. "/" .. ipkg .. ".ipk"
            if nixio.fs.stat(file) then
                os.execute("opkg install " .. file)
            end
        elseif state == "global" then
            os.execute("opkg install " .. ipkg)
        end
    end
end

-- Don't do this again
os.remove("/etc/cron.boot/reinstall-packages")
