#!/bin/sh
# Give specific interfaces unique ipv4 & ipv6 link local address

RETRIES=10
TESTS=2

case "${INTERFACE}" in
    wg*|xlink*|remoterf*)
        if "${ACTION}" = "ifup"; then
            if ! /sbin/ip -4 addr show dev ${DEVICE} scope link | /bin/grep -q "inet "; then
                n=0
                while [ ${n} -lt ${RETRIES} ]; do
                    IP="169.254.$(( ($(/usr/bin/hexdump -n2 -e '"%u"' /dev/urandom) % 254) + 1 )).$(( $(/usr/bin/hexdump -n1 -e '"%u"' /dev/urandom) ))"
                    if ! /sbin/ip -4 -o addr show | /bin/grep -qw ${IP} && /usr/sbin/arping -q -c ${TESTS} -D -I ${DEVICE} ${IP}; then
                        /sbin/ip -4 addr add ${IP}/16 dev ${DEVICE} scope link
                        break
                    fi
                    n=$((n+1))
                done
            fi
            if ! /sbin/ip -6 -o addr show dev ${DEVICE} scope link | /bin/grep -q "inet6 fe80:"; then
                IP="fe80::$(/usr/bin/hexdump -n2 -e '"%04x"' /dev/urandom):$(/usr/bin/hexdump -n2 -e '"%04x"' /dev/urandom):$(/usr/bin/hexdump -n2 -e '"%04x"' /dev/urandom):$(/usr/bin/hexdump -n2 -e '"%04x"' /dev/urandom)"
                /sbin/ip -6 addr add ${IP}/64 dev ${DEVICE} scope link 2>/dev/null
            fi
        fi
        ;;
    *)
        ;;
esac
