#!/bin/sh

xlink=$(uci -q -c /etc/config.mesh/ show xlink | grep "ifname='${DEVICE}'")

# This section will generate rtnetlink errors when the rule doesn't exist.
# This will be most common in the case of ifup.
# On initial boot no route will be present, and on most interface restarts
# the route should already be gone from ifdown but some scripts do not call
# ifup/ifdown  to control the interface so we will want to make sure to
# run a clean before hand to avoid duplicate rules.

if [ "$ACTION" = "ifdown" ] || [ "$ACTION" = "ifup" ] ; then

  echo "Deleting specific routing rules that may exist."

  if [ "$INTERFACE" == "wifi" ] || [ "$INTERFACE" == "dtdlink" ] || [ "${INTERFACE:0:3}" == "tun" ] || [ "${INTERFACE:0:2}" = "wg" ] || [ "$xlink" != "" ] ; then
    ip rule del pref 20010 iif $DEVICE lookup 29
    ip rule del pref 20020 iif $DEVICE lookup 20
    ip rule del pref 20040 iif $DEVICE lookup 21
    ip rule del pref 20050 iif $DEVICE lookup 22
    ip rule del pref 20090 iif $DEVICE lookup main
    ip rule del pref 20099 iif $DEVICE unreachable 
  fi

  if [ "$INTERFACE" == "lan" ] ; then
    ip rule del pref 30010 iif $DEVICE lookup 29
    ip rule del pref 30020 iif $DEVICE lookup 20
    ip rule del pref 30040 iif $DEVICE lookup 21
    ip rule del pref 30050 iif $DEVICE lookup main
    ip rule del pref 30070 iif $DEVICE lookup 22
  fi

  if [ "$INTERFACE" == "loopback" ] ; then
    ip rule del pref 30210 lookup 29
    ip rule del pref 30220 lookup 20
    ip rule del pref 30240 lookup 21
    ip rule del pref 30260 lookup main
    ip rule del pref 30270 lookup 22
  fi

fi

if [ "$ACTION" = "ifup" ] ; then

  is_wan_gw=$(/sbin/uci -q get aredn.@wan[0].mesh_to_local_wan) # MESH -> WAN
  is_mesh_wan_gw=$(/sbin/uci -q get aredn.@wan[0].lan_to_remote_wan) # LAN -> MESH-WAN

  # Set routes for wifi or device to device linking
  # unreachable rule is needed  to ensure packets do not traverse a rule later that considers routing to another network.

  echo "Setting routing rules."

  if [ "$INTERFACE" == "wifi" ] || [ "$INTERFACE" == "dtdlink" ] || [ "${INTERFACE:0:3}" = "tun" ] || [ "${INTERFACE:0:2}" = "wg" ] || [ "$xlink" != "" ]; then
    ip rule add pref 20010 iif $DEVICE lookup 29
    ip rule add pref 20020 iif $DEVICE lookup 20
    ip rule add pref 20040 iif $DEVICE lookup 21
    ip rule add pref 20050 iif $DEVICE lookup 22
    if [ $is_wan_gw -eq 1 ] ; then
      ip rule add pref 20090 iif $DEVICE lookup main
    fi
    ip rule add pref 20099 iif $DEVICE unreachable

  fi

  if [ "$INTERFACE" = "wan" ] && [ $is_wan_gw -eq 1 ]; then
    wangwip=$(ip route get 8.8.8.8 | sed -e 's/.*via//' -e 's/ dev.*//')
    ip route add default via $wangwip table 28
  fi

  # Makes sure the lan interface is allowed to hit the local interfaces(29), babel(20), and local routes (main)  Local ethernet is trusted to use additonal rules.
  if [ "$INTERFACE" == "lan" ] ; then
    ip rule add pref 30010 iif $DEVICE lookup 29
    ip rule add pref 30020 iif $DEVICE lookup 20
    ip rule add pref 30040 iif $DEVICE lookup 21
    ip rule add pref 30050 iif $DEVICE lookup main
    if [ $is_mesh_wan_gw -eq 1 ]; then
      ip rule add pref 30070 iif $DEVICE lookup 22
    fi

    # Lets go ahead and set the route to the local network here since we only need to be able to route to it after the interface comes up.
    lan_ipaddr=$(uci -q get network.lan.ipaddr)
    lan_netmask=$(uci -q get network.lan.netmask)
    bridge=$(uci -q get network.lan.type)
    if [ $bridge = "bridge" ] ; then
        lan_ifname="br-lan"
    else
        lan_ifname=$(uci -q get network.lan.device | cut -f1)
    fi
    if [ "$lan_ifname" != "" ] && [ "$lan_ipaddr" != "" ] && [ "$lan_netmask" != "" ] ; then
      lan_networkip=$(ipcalc.sh $lan_ipaddr $lan_netmask|grep NETWORK|cut -d'=' -f2)
      ip route add $lan_networkip/$lan_netmask table 29 dev $lan_ifname
    fi

  fi

  # Handles setting up rules for local resolution of routes.
  if [ "$INTERFACE" == "loopback" ] ; then
    ip rule add pref 30210 lookup 29
    ip rule add pref 30220 lookup 20
    ip rule add pref 30240 lookup 21
    ip rule add pref 30260 lookup main
    ip rule add pref 30270 lookup 22
  fi

fi

# Ensure we send a good exit code
exit 0;

