#!/bin/sh

BABEL_PORT=6697
BABEL_PATH=/var/run/babel.sock

case "${ACTION}" in
    ifdown)
        socat - UNIX-CLIENT:${BABEL_PATH} <<__END__
flush interface ${DEVICE}
__END__
        ;;
    ifup)
        XLINK=$(uci -q show network | grep "xlink.*ifname='${DEVICE}'")
        if [ "${XLINK}" != "" ]; then
            socat - UNIX-CLIENT:${BABEL_PATH} <<__END__
interface ${DEVICE} type auto
__END__
        elif [ "${INTERFACE}" == "wifi" ]; then
            if [ "${DEVICE}" == "br-nomesh" ]; then
                socat - UNIX-CLIENT:${BABEL_PATH} <<__END__
interface ${DEVICE} type wired
interface ${DEVICE} rxcost $(uci get babel.wired.rxcost)
interface ${DEVICE} split-horizon $(uci get babel.wired.split_horizon)
__END__
            else
                socat - UNIX-CLIENT:${BABEL_PATH} <<__END__
interface ${DEVICE} type wireless
interface ${DEVICE} link-quality true
interface ${DEVICE} rxcost $(uci get babel.wireless.rxcost)
interface ${DEVICE} unicast $(uci get babel.wireless.unicast)
__END__
            fi
        elif [ "${INTERFACE}" == "dtdlink" ] ; then
            socat - UNIX-CLIENT:${BABEL_PATH} <<__END__
interface ${DEVICE} type wired
interface ${DEVICE} rxcost $(uci get babel.wired.rxcost)
interface ${DEVICE} split-horizon $(uci get babel.wired.split_horizon)
__END__
        elif [ "${INTERFACE:0:3}" = "tun" ] || [ "${INTERFACE:0:2}" = "wg" ]; then
            socat - UNIX-CLIENT:${BABEL_PATH} <<__END__
interface ${DEVICE} type tunnel
interface ${DEVICE} rxcost $(uci get babel.tunnel.rxcost)
interface ${DEVICE} enable-timestamps true
interface ${DEVICE} max-rtt-penalty $(uci get babel.tunnel.max_rtt_penalty)
__END__
        fi
        ;;
    *)
        ;;
esac
