#!/bin/sh
# Handles setting up rules for extra interfaces

islink=$(uci -q -c /etc/config.mesh/ show xlink | grep "ifname='${INTERFACE}'")
if [ "${islink}" != "" ]; then
    if [ ${ACTION} = "ifup" ] ; then
        /usr/local/bin/vtun_up ${INTERFACE} up
    elif [ ${ACTION} = "ifdown" ] ; then
        /usr/local/bin/vtun_up ${INTERFACE} down
    fi
fi
